import {
  AndroidConfig,
  ConfigPlugin,
  withAndroidManifest,
  withDangerousMod,
  withFinalizedMod,
} from '@expo/config-plugins';
import * as fs from 'fs';
import { createRequire } from 'module';
import * as path from 'path';

export type AndroidAutoUsesName = 'template' | 'media' | 'notification';

export type CarPlayAndroidPluginProps = {
  /** Generate the optional react-native-background-geolocation bridge. */
  backgroundGeolocation?: boolean;
  androidAuto?: {
    /** Register the host as Android-Auto-aware. Default: true. */
    register?: boolean;
    /** Default: `template`. */
    usesName?: AndroidAutoUsesName;
  };
};

const META_NAME = 'com.google.android.gms.car.application';
const META_RESOURCE = '@xml/automotive_app_desc';
const RESOURCE_FILE = 'automotive_app_desc.xml';
const MARKER = 'Generated by expo-detect-carplay';

export function getAndroidCarPlayPluginKotlin(packageName: string): string {
  return `\
package ${packageName}

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Log
import com.transistorsoft.locationmanager.adapter.BackgroundGeolocation
import com.transistorsoft.locationmanager.adapter.callback.TSCallback
import com.transistorsoft.locationmanager.adapter.callback.TSLocationCallback
import com.transistorsoft.locationmanager.adapter.callback.TSSyncCallback
import com.transistorsoft.locationmanager.data.LocationModel
import com.transistorsoft.locationmanager.location.TSCurrentPositionRequest
import com.transistorsoft.locationmanager.location.TSLocation
import expo.modules.detectcarplay.CarPlayEventPlugin

class CarPlayGeoPlugin(context: Context) : CarPlayEventPlugin {
  companion object {
    private const val TAG = "CarPlayGeoPlugin"
    private const val STOP_GRACE_MS = 30_000L
  }

  private val appContext = context.applicationContext
  private val bgGeo = BackgroundGeolocation.getInstance(appContext, null)
  private val mainHandler = Handler(Looper.getMainLooper())
  private var trackingRequested = false
  private var stopInFlight = false
  private var lifecycleGeneration = 0L
  private var pendingFinalization: Runnable? = null

  private fun logFailure(operation: String, error: Any) {
    Log.e(TAG, "$operation failed: $error")
  }

  private fun loggedCallback(operation: String) = object : TSCallback {
    override fun onSuccess() {}
    override fun onFailure(error: String) = logFailure(operation, error)
  }

  private fun runOnMain(block: () -> Unit) {
    if (Looper.myLooper() == Looper.getMainLooper()) block() else mainHandler.post(block)
  }

  private fun cancelPendingFinalization() {
    pendingFinalization?.let(mainHandler::removeCallbacks)
    pendingFinalization = null
  }

  private fun canFinalize(generation: Long) =
    !trackingRequested && generation == lifecycleGeneration

  private fun ensureTrackingStarted() {
    if (!trackingRequested || stopInFlight) return
    bgGeo.start(object : TSCallback {
      override fun onSuccess() = runOnMain {
        if (trackingRequested && !stopInFlight) {
          bgGeo.changePace(true, loggedCallback("changePace(true)"))
        }
      }

      override fun onFailure(error: String) = logFailure("start", error)
    })
  }

  private fun requestFinalPosition(generation: Long) {
    if (!canFinalize(generation)) return
    val builder = TSCurrentPositionRequest.Builder(appContext)
    builder.setPersist(true)
    builder.setCallback(object : TSLocationCallback {
      override fun onLocation(location: TSLocation) = runOnMain {
        changeToStationary(generation)
      }

      override fun onError(errorCode: Int) = runOnMain {
        logFailure("getCurrentPosition", errorCode)
        changeToStationary(generation)
      }
    })
    bgGeo.getCurrentPosition(builder.build())
  }

  private fun changeToStationary(generation: Long) {
    if (!canFinalize(generation)) return
    bgGeo.changePace(false, object : TSCallback {
      override fun onSuccess() = runOnMain { syncAndStop(generation) }

      override fun onFailure(error: String) = runOnMain {
        logFailure("changePace(false)", error)
        syncAndStop(generation)
      }
    })
  }

  private fun syncAndStop(generation: Long) {
    if (!canFinalize(generation)) return
    bgGeo.sync(object : TSSyncCallback {
      override fun onSuccess(records: MutableList<LocationModel>) = runOnMain {
        stopTracking(generation)
      }

      override fun onFailure(error: String) = runOnMain {
        logFailure("sync", error)
        stopTracking(generation)
      }
    })
  }

  private fun stopTracking(generation: Long) {
    if (!canFinalize(generation)) return
    stopInFlight = true
    bgGeo.stop(object : TSCallback {
      override fun onSuccess() = finishStop()

      override fun onFailure(error: String) {
        logFailure("stop", error)
        finishStop()
      }
    })
  }

  private fun finishStop() = runOnMain {
    stopInFlight = false
    if (trackingRequested) ensureTrackingStarted()
  }

  override fun onCarPlayConnected(transport: String) = runOnMain {
    lifecycleGeneration += 1
    cancelPendingFinalization()
    val wasTrackingRequested = trackingRequested
    trackingRequested = true
    if (!wasTrackingRequested) {
      ensureTrackingStarted()
    } else if (!stopInFlight) {
      bgGeo.changePace(true, loggedCallback("changePace(true)"))
    }
  }

  override fun onCarPlayDisconnected() = runOnMain {
    if (!trackingRequested) return@runOnMain
    lifecycleGeneration += 1
    val generation = lifecycleGeneration
    cancelPendingFinalization()
    val finalization = Runnable {
      if (generation != lifecycleGeneration || !trackingRequested) return@Runnable
      pendingFinalization = null
      trackingRequested = false
      requestFinalPosition(generation)
    }
    pendingFinalization = finalization
    mainHandler.postDelayed(finalization, STOP_GRACE_MS)
  }
}
`;
}

function descriptorPath(platformProjectRoot: string): string {
  return path.join(platformProjectRoot, 'app/src/main/res/xml', RESOURCE_FILE);
}

function isOwned(platformProjectRoot: string): boolean {
  try {
    return fs.readFileSync(descriptorPath(platformProjectRoot), 'utf8').includes(MARKER);
  } catch {
    return false;
  }
}

const withRegistration =
  (usesName: AndroidAutoUsesName): ConfigPlugin =>
  (config) => {
    config = withAndroidManifest(config, (cfg) => {
      const existing = AndroidConfig.Manifest.getMainApplicationMetaDataValue(
        cfg.modResults,
        META_NAME
      );
      if (existing == null) {
        const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
        AndroidConfig.Manifest.addMetaDataItemToMainApplication(
          app,
          META_NAME,
          META_RESOURCE,
          'resource'
        );
      }
      return cfg;
    });
    return withDangerousMod(config, [
      'android',
      (cfg) => {
        const file = descriptorPath(cfg.modRequest.platformProjectRoot);
        if (!fs.existsSync(file) || isOwned(cfg.modRequest.platformProjectRoot)) {
          fs.mkdirSync(path.dirname(file), { recursive: true });
          fs.writeFileSync(
            file,
            `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${MARKER} -->\n<automotiveApp>\n    <uses name="${usesName}"/>\n</automotiveApp>\n`
          );
        }
        return cfg;
      },
    ]);
  };

const withoutRegistration: ConfigPlugin = (config) => {
  config = withAndroidManifest(config, (cfg) => {
    if (!isOwned(cfg.modRequest.platformProjectRoot)) return cfg;
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults) as any;
    app['meta-data'] = (app['meta-data'] ?? []).filter(
      (entry: any) =>
        entry?.$?.['android:name'] !== META_NAME || entry?.$?.['android:resource'] !== META_RESOURCE
    );
    return cfg;
  });
  return withFinalizedMod(config, [
    'android',
    (cfg) => {
      const file = descriptorPath(cfg.modRequest.platformProjectRoot);
      if (fs.existsSync(file) && isOwned(cfg.modRequest.platformProjectRoot)) {
        fs.rmSync(file);
      }
      return cfg;
    },
  ]);
};

function assertBackgroundGeolocationInstalled(projectRoot: string): void {
  try {
    createRequire(path.join(projectRoot, 'package.json')).resolve(
      'react-native-background-geolocation'
    );
  } catch {
    throw new Error(
      '[expo-detect-carplay] backgroundGeolocation: true requires react-native-background-geolocation to be installed.'
    );
  }
}

function sourceRoot(platformRoot: string, packageName: string): string {
  return path.join(platformRoot, 'app/src/main/java', packageName.replace(/\./g, '/'));
}

function modifyMainApplication(contents: string): string {
  const importLine = 'import expo.modules.detectcarplay.CarPlayPluginRegistry';
  if (!contents.includes(importLine)) {
    const lines = contents.split('\n');
    const lastImport = lines.reduce(
      (last, line, index) => (line.trimStart().startsWith('import ') ? index : last),
      -1
    );
    lines.splice(lastImport + 1, 0, `${importLine} // expo-detect-carplay-generated`);
    contents = lines.join('\n');
  }
  const call = 'CarPlayPluginRegistry.register(CarPlayGeoPlugin(this))';
  if (!contents.includes(call)) {
    contents = contents.replace(/(super\.onCreate\(\)[ \t]*)(\r?\n)/, `$1$2    ${call}$2`);
  }
  return contents;
}

function unmodifyMainApplication(contents: string): string {
  contents = contents.replace(
    /^[ \t]*CarPlayPluginRegistry\.register\(CarPlayGeoPlugin\(this\)\)\r?\n/gm,
    ''
  );
  const generatedImport =
    /^import expo\.modules\.detectcarplay\.CarPlayPluginRegistry \/\/ expo-detect-carplay-generated\r?\n/m;
  const withoutImport = contents.replace(generatedImport, '');
  if (!/\bCarPlayPluginRegistry\b/.test(withoutImport)) contents = withoutImport;
  return contents;
}

const withGeoPlugin: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      assertBackgroundGeolocationInstalled(cfg.modRequest.projectRoot);
      const packageName = cfg.android?.package;
      if (!packageName) return cfg;
      const root = sourceRoot(cfg.modRequest.platformProjectRoot, packageName);
      fs.mkdirSync(root, { recursive: true });
      fs.writeFileSync(
        path.join(root, 'CarPlayGeoPlugin.kt'),
        getAndroidCarPlayPluginKotlin(packageName)
      );
      const mainApplication = path.join(root, 'MainApplication.kt');
      if (fs.existsSync(mainApplication)) {
        fs.writeFileSync(
          mainApplication,
          modifyMainApplication(fs.readFileSync(mainApplication, 'utf8'))
        );
      }
      return cfg;
    },
  ]);

const withoutGeoPlugin: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const packageName = cfg.android?.package;
      if (!packageName) return cfg;
      const root = sourceRoot(cfg.modRequest.platformProjectRoot, packageName);
      const generated = path.join(root, 'CarPlayGeoPlugin.kt');
      if (fs.existsSync(generated)) fs.rmSync(generated);
      const mainApplication = path.join(root, 'MainApplication.kt');
      if (fs.existsSync(mainApplication)) {
        const original = fs.readFileSync(mainApplication, 'utf8');
        const cleaned = unmodifyMainApplication(original);
        if (cleaned !== original) fs.writeFileSync(mainApplication, cleaned);
      }
      return cfg;
    },
  ]);

const withCarPlayAndroid: ConfigPlugin<CarPlayAndroidPluginProps | void> = (config, props) => {
  const options = props ?? {};
  config =
    options.androidAuto?.register === false
      ? withoutRegistration(config)
      : withRegistration(options.androidAuto?.usesName ?? 'template')(config);
  return options.backgroundGeolocation ? withGeoPlugin(config) : withoutGeoPlugin(config);
};

export const __androidCarPlayPluginInternals = {
  modifyMainApplication,
  unmodifyMainApplication,
};

export default withCarPlayAndroid;
